<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>B9PartSwitch</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>T:\Kerbal Space Program\KSP1.9.1\KSP_x64_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>T:\Kerbal Space Program\KSP1.9.1\KSP_x64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>T:\Kerbal Space Program\KSP1.9.1\KSP_x64_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>