public enum ClearToSaveStatus
{
	CLEAR,
	NOT_IN_ATMOSPHERE,
	NOT_UNDER_ACCELERATION,
	NOT_WHILE_MOVING_OVER_SURFACE,
	NOT_WHILE_ABOUT_TO_CRASH,
	NOT_WHILE_ON_A_LADDER,
	NOT_WHILE_THROTTLED_UP,
	ORBIT_EVENT_IMMINENT
}
