public enum ResourceFlowMode
{
	NO_FLOW,
	ALL_VESSEL,
	STAGE_PRIORITY_FLOW,
	STACK_PRIORITY_SEARCH,
	ALL_VESSEL_BALANCE,
	STAGE_PRIORITY_FLOW_BALANCE,
	STAGE_STACK_FLOW,
	STAGE_STACK_FLOW_BALANCE,
	NULL
}
