<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KerbalEngineer.Unity</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.UIModule" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.UI" />
    <Reference Include="UnityEngine.TextRenderingModule" />
  </ItemGroup>
</Project>