namespace DDSHeaders;

public enum D3D10_RESOURCE_DIMENSION : uint
{
	D3D11_RESOURCE_DIMENSION_UNKNOWN,
	D3D11_RESOURCE_DIMENSION_BUFFER,
	D3D11_RESOURCE_DIMENSION_TEXTURE1D,
	D3D11_RESOURCE_DIMENSION_TEXTURE2D,
	D3D11_RESOURCE_DIMENSION_TEXTURE3D
}
